version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '80:80'
  node-app:
    build:
      context: .
      args:
        NODE_ENV: production
    container_name: node-app
    environment:
      - PORT=${PORT}
      - NODE_ENV=production
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=password
    command: pm2-runtime ecosystem.config.js --env production
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./mongo:/data/db
