version: '3'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '4000:80'
    depends_on:
      - node-app
    restart: always
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    container_name: node-app
    environment:
      - PORT=5000
      - NODE_ENV=development
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
    command: npm run dev
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - ./mongo:/data/db
