name: node-devops

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - run: |
          export PORT=${{ PORT }}
          export NODE_ENV=${{ NODE_ENV }}
          export MONGO_USERNAME=${{ MONGO_USERNAME }}
          export MONGO_PASSWORD=${{ MONGO_PASSWORD }}
          export MONGO_INITDB_ROOT_USERNAME=${{ MONGO_INITDB_ROOT_USERNAME }}
          export MONGO_INITDB_ROOT_PASSWORD=${{ MONGO_INITDB_ROOT_PASSWORD }}
      - run: docker-compose -f docker-compose.prod.yml down
      - run: docker-compose -f docker-compose.prod.yml up -d --build
