name: node-devops

on:
  push:
    branches: ['master']

jobs:
  build:
    runs-on: self-hosted
    env:
      PORT: ${{ secrets.PORT }}
    steps:
      - uses: actions/checkout@v3
      - run: docker-compose -f docker-compose.prod.yml down
      - run: docker-compose -f docker-compose.prod.yml up -d --build
